FEAT: Add `safe_merge` option in `merge`
huggingface/peft pull request #1001
Opened 2023-10-06 15:28 UTC by younesbelkada

# What does this PR do?

Analogous PR to https://github.com/huggingface/diffusers/pull/5316 

Some users that use diffusion models can face strange issues when merging the adapter weights inside the base model. This PR is the PEFT equivalent of @patrickvonplaten 's PR on diffusers

I would advocate to default `safe_merge` to `False` as this PR adds an overhead. in fact, it is preferable to first copy the merged tensor, check if there is any `nan` value there and raise a proper `ValueError` in case there is a `nan`. Otherwise the potential `nan` would be already propagated to the merged weights before raising the error

Added also nice tests

cc @pacman100 @BenjaminBossan @sayakpaul @patrickvonplaten FYI --> on https://github.com/huggingface/diffusers/pull/5151 we would just pass `safe_merge=safe_merge` in `module.merge`

2023-10-06 15:32 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_1001). All of your documentation changes will be reflected on that endpoint.

2023-10-06 15:49 UTC, BenjaminBossan commented
This looks like a useful feature to have, thanks for the addition.

For my understanding, the NaN could also be caused by the _addition_ of the delta weights, even if those don't contain any NaN themselves, and that's why you perform the check on the merged weights, not on the delta weights, right? The main reason I'm asking is because if we only do the check on the delta weights, we wouldn't need to create a copy of the original weights.

Btw. IIRC the test that was failing was not the flaky one, so there might be some fixing needed. Could be caused by the changed line `if active_adapter not in self._active_adapter:`.

2023-10-06 15:53 UTC, younesbelkada commented
Indeed @BenjaminBossan I believe the overflow (`nan`) is purely caused by the sum between the adapter weights and the base model, I also think this usually happens under `float16` regime. 
It could be potentially caused by nan being in the delat weights but it is also likely that the sum causes the overflow afterward, therefore I think it is safer to perform the check this way. Let me know what do you think
Regarding your second point that's correct as well !

2023-10-09 10:32 UTC, younesbelkada commented on tests/testing_common.py
> +        with self.assertRaises(ValueError):
Yes, done!

2023-10-09 10:32 UTC, younesbelkada commented on src/peft/tuners/lora/layer.py
> +                    if torch.isnan(orig_weights).any().item():
I think it is not needed indeed

2023-10-09 10:52 UTC, BenjaminBossan reviewed
Thanks for addressing the comments. I found two more type annotations that need fixing which I missed the first time around, otherwise LGTM.

2023-10-09 10:52 UTC, BenjaminBossan commented on src/peft/tuners/lora/layer.py
> +    def merge(self, safe_merge: Optional[bool] = False) -> None:
```suggestion
    def merge(self, safe_merge: bool = False) -> None:
```

2023-10-09 10:52 UTC, BenjaminBossan commented on src/peft/tuners/lora/layer.py
> +    def merge(self, safe_merge: Optional[bool] = False) -> None:
```suggestion
    def merge(self, safe_merge: bool = False) -> None:
```

2023-10-09 10:55 UTC, younesbelkada commented
Thanks very much for all the reviews @BenjaminBossan !

2023-10-09 11:02 UTC, BenjaminBossan approved these changes
Thanks a lot, this now looks ready to me (once CI is green).

We may want to add the option for safe merging to the other adapters too. Maybe we can create an issue so that it's not forgotten?

2023-10-09 11:03 UTC, younesbelkada commented
I think that we should add it in this PR to make things consistent, let me work on that!

2023-10-09 11:41 UTC, patrickvonplaten commented
Cool!

2023-10-09 14:12 UTC, BenjaminBossan requested changes
Thanks a lot for adding the safe merging feature to the other methods. It is still missing for LoRA bnb layers, which support merging. It would be fine with me if they are added in a separate PR though.

I noticed some more things only now, sorry for not noticing earlier:

1. The error message

> NaNs detected in the merged weights. The Lora adapter {active_adapter} seems to be broken and should be removed

is a bit confusing IMO. The issue I see is with suggesting to remove it, because (if I'm not mistaken) it is totally possible for the adapter layer to be working in `forward` when applied separately from the original weights, and only encountering NaNs after merging, since the mathematical operation is not identical. E.g. two weight parameters could be overflowing when added, but when they are both first multiplied by the activation and only then added, they might not overflow anymore.

Therefore, I wouldn't ask to remove the adapter, as it may work. Instead, I would change the message to just say that this adapter cannot be merged safely, without any further suggestion. WDYT?

2. `torch.isnan` check

The next issue I only noticed just now is that I think we should not check with `torch.isnan` because it doesn't include `torch.inf`. Instead, `torch.isfinite(x).all()` should work for both `torch.inf` and `torch.nan`. WDYT? If you agree, maybe the test could be extended to also include `module.data[0] = torch.inf`.



lora bnb layers

use torch.isfinite(x).all() instead

2023-10-09 14:44 UTC, younesbelkada commented
@BenjaminBossan all the proposed suggestions sound great to me ! Will work on that

2023-10-09 14:55 UTC, younesbelkada commented
I have adapted the changes accordingly and added a test case with inf, let me know what do you think!

2023-10-09 15:00 UTC, BenjaminBossan approved these changes
Looks great. Thanks for addressing the remaining issues. From my point of view, it can be merged once CI is green.

2023-10-09 16:28 UTC, merged