Fix ModulesToSaveWrapper __getattr__
huggingface/peft pull request #1238
Opened 2023-12-08 01:25 UTC by zhangsheng377

https://github.com/huggingface/peft/issues/1225

We are recently using peft=0.4.0+Megatron to run GPTModel. There is a code of the model [`self.language_model.output_layer.weight`](https://github.com/NVIDIA/Megatron-LM/blob/bcce6f54e075e3c3374ea67adefe54f3f2da2b07/megatron/model/gpt_model.py#L94), which directly takes the `weight` of the `output_layer`, but the `output_layer` has already been `modules_to_save`, so it reported "ModulesToSaveWrapper has no 'weight' attribute" error.

So, I returns the weight of the currently active adapter or of the original module of the adapter is deactivated. 

And `__getattr__` will be called only when its own class does not have this attribute, so this should not destroy the original scene.

2023-12-08 13:04 UTC, BenjaminBossan requested changes
Thanks for the PR. Thinking a bit more about it, I think the best course of action would be to actually implement this as a `@property`, which allows us to avoid fiddling with `__getattr__`.

This should still not affect stuff like `state_dict`, so would not break anything.

On top of that, would you be up to implement a unit test?

2023-12-11 03:56 UTC, zhangsheng377 commented
> Thanks for the PR. Thinking a bit more about it, I think the best course of action would be to actually implement this as a `@property`, which allows us to avoid fiddling with `__getattr__`.
> 
> This should still not affect stuff like `state_dict`, so would not break anything.
> 
> On top of that, would you be up to implement a unit test?

ok~

2023-12-11 11:30 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_1238). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2023-12-11 14:36 UTC, BenjaminBossan approved these changes
Thanks, LGTM.

Can one of you @pacman100 or @younesbelkada give this a quick look to ensure it doesn't break anything?

2023-12-13 11:08 UTC, pacman100 approved these changes
Thank you @zhangsheng377 for adding the weight property when using `ModulesToSaveWrapper`! This makes sense and I don't see any issues with this approach.

2023-12-13 11:52 UTC, merged

2023-12-13 11:58 UTC, younesbelkada commented
Tests are all green! https://github.com/huggingface/peft/actions/runs/7194802375/job/19596105974 🍏