LoftQ: update example files and README
huggingface/peft pull request #1344
Opened 2024-01-10 15:48 UTC by yxli2123

Hi, I would like to update some example files and README files in example/loftq_finetuning.

2024-01-10 16:25 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_1344). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-01-10 16:49 UTC, BenjaminBossan requested changes
Thanks for the update. I have a few comments/suggestions. Also, could you please run `make style`?

2024-01-10 16:49 UTC, BenjaminBossan commented on examples/loftq_finetuning/quantize_save_load.py
> +    # convert safetensor to bin
Hmm, why is this needed? Also, would `lora_model.save_pretrained(lora_model_dir, safe_serialization=False)` also work?

2024-01-10 16:49 UTC, BenjaminBossan commented on examples/loftq_finetuning/quantize_save_load.py
> +        adapter_config['init_lora_weights'] = True  # Don't apply LoftQ when loading again
Interesting, I wonder if this is a wider use case?

2024-01-10 16:49 UTC, BenjaminBossan commented on examples/loftq_finetuning/quantize_save_load.py
> +    # change adapter_config.json
Instead of loading and overwriting the file, would it make more sense to set the attributes correctly before even saving the adapter?

2024-01-10 16:49 UTC, BenjaminBossan commented on examples/loftq_finetuning/train_gsm8k.py
> +
I haven't reviewed this script. Is it just the same as `train_gsm8k_llama.py`?

2024-03-01 09:56 UTC, BenjaminBossan commented
@yxli2123 What is the state of the PR?

2024-03-01 14:03 UTC, yxli2123 commented
It should be closed, thanks

> On Mar 1, 2024, at 5:56 PM, Benjamin Bossan ***@***.***> wrote:
> 
> 
> @yxli2123 <https://github.com/yxli2123> What is the state of the PR?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/huggingface/peft/pull/1344#issuecomment-1972873131>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQQKA2QBURYKLDOZUIZ7JLLYWBGEPAVCNFSM6AAAAABBVANW46VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZSHA3TGMJTGE>.
> You are receiving this because you were mentioned.
>

2024-03-04 01:24 UTC, closed without merging