[docs] IA3
huggingface/peft pull request #1373
Opened 2024-01-19 01:00 UTC by stevhliu

Adds a guide for IA3 to the docs. The `IA3Config` is pretty barebones so feel free to suggest any improvements to it!

2024-01-19 01:04 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_1373). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-01-24 10:07 UTC, younesbelkada approved these changes
Thanks a lot !

2024-01-24 18:52 UTC, stevhliu commented
Thanks! I'll wait for one more review from @BenjaminBossan when he returns from vacation before merging!

2024-01-29 08:00 UTC, pacman100 approved these changes
Thank you @stevhliu for adding a task guide on IA3 method! 🔥🚀✨

Left a few suggestions/comments.

2024-02-06 10:26 UTC, BenjaminBossan requested changes
Thanks a lot for adding the IA³ guide. Overall, it looks good. I would suggest to add just a couple of more lines of code to make it so that users can just copy and paste the code and it runs. WDYT?

2024-02-06 10:26 UTC, BenjaminBossan commented on docs/source/task_guides/ia3.md
> +ds = load_dataset("financial_phrasebank", "sentences_allagree")
Let's add the import `from datasets import load_dataset`.

2024-02-06 10:26 UTC, BenjaminBossan commented on docs/source/task_guides/ia3.md
> +train_ds = processed_ds["train"]
Let's add the imports: 

```
from torch.utils.data import DataLoader
from transformers import default_data_collator
```

2024-02-06 10:26 UTC, BenjaminBossan commented on docs/source/task_guides/ia3.md
> +from peft import IA3Config
```suggestion
from peft import IA3Config, get_peft_model
```

2024-02-06 10:26 UTC, BenjaminBossan commented on docs/source/task_guides/ia3.md
> +lr = 8e-3
let's add the imports:

```
import torch
from transformers import get_linear_schedule_with_warmup
```

2024-02-06 10:26 UTC, BenjaminBossan commented on docs/source/task_guides/ia3.md
> +model = model.to("cuda")
This block misses `from tqdm import tqdm` and `device = "cuda"`.

2024-02-06 10:26 UTC, BenjaminBossan commented on docs/source/task_guides/ia3.md
> +model = AutoPeftModelForSeq2SeqLM.from_pretrained("stevhliu/mt0-large-ia3").to("cuda")
Should "stevhliu" be replaced here by `<your-hf-account-name>` for consistency with the snippet above?

2024-02-07 10:15 UTC, BenjaminBossan approved these changes
Thanks for making the adjustments quickly. LGTM.

2024-02-07 19:49 UTC, merged