fix: fail when required args not passed when prompt_tuning_init==TEXT
huggingface/peft pull request #1519
Opened 2024-03-01 07:59 UTC by kmehant

When `prompt_tuning_init==TEXT` is set, there are some args needed to be provided. For instance, `tokenizer_name_or_path` should be set to some tokenizer name or path, failing which would result in errors such as

```
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/None/resolve/main/tokenizer_config.json
```
tokenizer_name_or_path is taken as `None`. Such errors can be handled and reported meaningfully post config initialization and this PR makes that contribution.

2024-03-01 09:54 UTC, BenjaminBossan commented
Thanks for adding this quality of life feature. Two points:

- Could you please break the long lines? We want to keep a 120 char limit.
- Would you mind adding tests to check that the error is raised? We can help with that if needed.

2024-03-01 10:17 UTC, kmehant commented
@BenjaminBossan 

> Would you mind adding tests to check that the error is raised? We can help with that if needed.


Sure @BenjaminBossan, I tried looking for tests for prompt tuning implementation, but I could not find them, can you point me to that?

2024-03-01 10:24 UTC, BenjaminBossan commented
> I tried looking for tests for prompt tuning implementation, but I could not find them, can you point me to that?

The tests are a bit scattered around, as we group by model architecture and not by method. But a good fit would be to add them to `tests/test_initialization.py`.

2024-03-01 11:05 UTC, kmehant commented
@BenjaminBossan Have added the tests and made required changes.

![Screenshot 2024-03-01 at 4 35 15 PM](https://github.com/huggingface/peft/assets/15800200/70cdccf3-cdfd-42cb-9485-53e049486d4d)

2024-03-01 14:31 UTC, BenjaminBossan commented
Thanks a lot for adding the test, could you please run `make style` and push the changes?

2024-03-04 05:28 UTC, kmehant commented
https://github.com/huggingface/peft/pull/1519#issuecomment-1973305566

@BenjaminBossan I have run `make style` and pushed the changes thanks.

2024-03-04 10:37 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_1519). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-03-05 11:07 UTC, BenjaminBossan requested changes
Thanks for the update. I found some very small things still, after that we should be good to go.

2024-03-05 14:07 UTC, merged