adding peft lora example notebook for ner
huggingface/peft pull request #2126
Opened 2024-10-04 12:52 UTC by JINO-ROHIT

Hi @BenjaminBossan , 

Ive added a lora example for NER, which is mainly a clone of the huggingface NER notebook by Sylvain here https://huggingface.co/learn/nlp-course/chapter7/2#data-collation with couple changes here and there.

lmk what you think

2024-10-07 10:12 UTC, BenjaminBossan requested changes
Context: #2119

Thanks @JINO-ROHIT for taking this task. Good find of a base notebook to adapt. @HarikrishnanK9 is this what you were looking for?

I haven't done a fine-grained analysis yet, but it looks like the `compute_metrics` are note being used. Therefore, we don't get the interesting metrics defined in there. Could you please check that?

2024-10-07 14:19 UTC, JINO-ROHIT commented
will do

2024-10-08 08:52 UTC, JINO-ROHIT commented
i added the eval metric part, the recall and precision seem quite low, seems to be the classes are imbalanced, would you like me to handle that?

2024-10-08 13:33 UTC, BenjaminBossan requested changes
Thanks a lot for the updates. I checked the notebook and found the source for the low performance, namely the learning rate. Check my comment.

Also, when I first ran this notebook, I got an error:

> ImportError: To be able to use evaluate-metric/seqeval, you need to install the following dependencies['seqeval'] using 'pip install seqeval' for instance'

So let's mention at the beginning which packages the user should install. We can assume that torch and PEFT (and all their dependencies) are installed, but besides `seqeval`, let's also mention `datasets` and `evaluate`.

Moreover, it would be nice to set the batch size to a higher value. The base model is quite small, so even with batch sizes of 32 or more, most users should be able to run the notebook. This will speed up training considerably. You can add a comment that users have to reduce the value if they run OOM.

2024-10-08 13:33 UTC, BenjaminBossan commented on examples/token_classification/peft_lora_ner.ipynb
> +    "peft_config = LoraConfig(target_modules = [\"query\", \"key\"])\n",
```suggestion
    "peft_config = LoraConfig(target_modules=[\"query\", \"key\"], task_type=TaskType.TOKEN_CLS))\n",
```

`TaskType` needs to be imported from PEFT.

2024-10-08 13:33 UTC, BenjaminBossan commented on examples/token_classification/peft_lora_ner.ipynb
> +    "    learning_rate=2e-5,\n",
The learning rate should be higher for LoRA. This is probably why you find worse results than expected. I checked  2e-4, 2e-3, and 2e-2, and got best results for 2e-3. However, they were still slightly worse than full fine-tuning and I only ran for 3 epochs, so some further experiments could yield better results still.

2024-10-08 13:33 UTC, BenjaminBossan commented on examples/token_classification/peft_lora_ner.ipynb
> +    "# Import required libraries\n",
Let's add a few sentences to the beginning before starting with the code. Something along the lines of: "In this notebook, we learn how to ...". You can also add the link to the course here.

2024-10-08 16:29 UTC, JINO-ROHIT commented
oh yeah, i totally missed the lr part. The metrics look waaay better now, thanks!

2024-10-08 16:43 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_2126). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-09 09:25 UTC, BenjaminBossan approved these changes
Thanks for adding this notebook to show NER with PEFT, LGTM.

From my point of view, it's ready to merge. I'll give @HarikrishnanK9 some time to take a look to possibly give more feedback. If we don't hear back by Friday, I'll merge.

2024-10-09 11:09 UTC, JINO-ROHIT commented
gotcha

2024-10-10 05:42 UTC, HarikrishnanK9 commented
@JINO-ROHIT Thank You @BenjaminBossan Just go ahead with the merge.

2024-10-10 09:04 UTC, merged