Fix: Add warning for adapter_name conflict with tuner
huggingface/peft pull request #2254
Opened 2024-12-03 16:28 UTC by pzdkn

This pull request addresses an [issue ](https://github.com/huggingface/peft/issues/2252) where adapter weights are incorrectly initialized when the adapter_name conflicts with the tuner_prefix during model loading. Specifically, it introduces a warning message to notify users when this conflict occurs, as this could lead to confusion or unintentional weight reinitialization.

**Changes:**

- Added a warning message when adapter_name matches the tuner_prefix, indicating a potential issue with missing adapter keys during model loading.
- The warning clarifies that this conflict is likely caused by the adapter_name being contained in the tuner_prefix, helping users identify and resolve the issue more easily.

**Impact:**

- Improves user experience by providing clearer feedback when model loading doesn't match expectations, preventing silent failures and making debugging easier.

2024-12-03 17:05 UTC, BenjaminBossan reviewed
Thanks for this PR. It is certainly not a bad idea to warn users if they come across this issue. I'd go even further and also add a warning when users first create a model with an overlapping adapter name. For that, we'd have to adjust:

- [`get_peft_model`](https://github.com/huggingface/peft/blob/c05758989d1a1bc650ab1f41fe1de34c88838731/src/peft/mapping.py#L146)
- [`add_adapter`](https://github.com/huggingface/peft/blob/c05758989d1a1bc650ab1f41fe1de34c88838731/src/peft/mapping.py#L146)

Would you be interested in working on those too? If not, I can later tackle this in a separate PR.

Regardless of that question, it would also be great to add a unit test for the warning (i.e. that there is no warning on the happy path but a warning when an overlapping name is chosen). [Here](https://github.com/huggingface/peft/blob/c05758989d1a1bc650ab1f41fe1de34c88838731/tests/test_initialization.py#L1756) is an example of a test that could be used as a starting point.

2024-12-04 10:30 UTC, pzdkn commented
Yes I'd happy to take that!

2024-12-04 14:18 UTC, pzdkn commented
Thanks for the guidance @BenjaminBossan ! I have added the warnings to both creation paths and the loading path plus an unit test.

2024-12-05 10:53 UTC, BenjaminBossan requested changes
Thanks a lot for adding the other warnings and for providing the unit tests. In general, this all looks very good. I just have a small request, which is to break the one long test into multiple smaller tests. This improves readability and makes the tests useful (right now, if one assert fails, the checks further below are not executed).

One way is just to split this function into multiple smaller function. This results in a bit of code duplication but that's okay. Another suggestion is to create a class for all these tests. Inside the class, you can have define a pytest fixture for the duplicate code (like the `model` and `config`, check [this test](https://github.com/huggingface/peft/blob/f86522e011af21697ef1477da4d232e74de83232/tests/test_initialization.py#L1514) as an example). I'll leave this decision up to you. LMK if you have any questions.

2024-12-06 12:35 UTC, pzdkn commented
Hi thanks for the tips @BenjaminBossan ! Hope this does the job now 😄

2024-12-10 10:54 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_2254). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-12-10 13:50 UTC, pzdkn commented
Done :+1:  Happy for another round of review @BenjaminBossan

2024-12-11 14:21 UTC, BenjaminBossan approved these changes
Thanks for adding the warnings for this edge case in naming, and for adding the nice unit tests. The PR LGTM.

Please ignore the failing CI, they're unrelated to the PR. We currently have trouble with the CI runners.

2024-12-11 14:23 UTC, merged