Use device_map to load adapters weight onto specified device
huggingface/peft pull request #725
Opened 2023-07-18 19:14 UTC by zhangyilun

When loading adapters weight with `PeftModel.from_pretrained(...)` method (https://github.com/huggingface/peft/blob/main/src/peft/peft_model.py#L553-L558), it will load the weights on the first visible cuda device, which might not always be ideal considering GPU memory allocation and management.

If a `device_map` variable (i.e. ` torch.device("cuda:2") is passed to `from_pretrained(...)` as kwargs, it can be used to ensure the weights are loaded to the specified device.

2023-07-19 11:52 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/peft/pr_725). All of your documentation changes will be reflected on that endpoint.

2023-07-19 14:14 UTC, zhangyilun commented
The change didn't pass code quality check. Can someone help me understand how is it failing?

```
Run make quality
black --check src tests examples docs
Skipping .ipynb files as Jupyter dependencies are not installed.
You can fix this by running ``pip install black[jupyter]``
would reformat src/peft/peft_model.py

Oh no! 💥 💔 💥
1 file would be reformatted, 43 files would be left unchanged.
make: *** [Makefile:9: quality] Error 1
Error: Process completed with exit code 2.
```

PS: this is my first time submitting PR.

2023-07-20 08:29 UTC, BenjaminBossan commented
Could you run `make style` locally? It should reformat `peft_model.py`.

2023-07-20 13:55 UTC, zhangyilun commented
@BenjaminBossan Thanks for the instruction, I have update the repo with the changes made by `make style`.

2023-08-01 09:09 UTC, BenjaminBossan approved these changes
Sorry for the late reply, this somehow slipped under my radar. In general, LGTM, 

There will be merge conflicts with other PRs, let's see what gets merged first.

2023-08-01 10:28 UTC, younesbelkada requested changes
Thanks for addressing this change! I think a stronger check needs to be added, `device_map` can indeed be a torch device but can be also an str or a dict. Maybe creating an utility function to process `device_map` and retrieve the intended device is needed

2023-08-01 10:28 UTC, younesbelkada commented on src/peft/peft_model.py
> +                filename, device=kwargs.get("device_map", "cuda" if torch.cuda.is_available() else "cpu")
What if someone passes `device_map="auto"`? I am not sure this change is robust enough

2023-08-01 10:29 UTC, younesbelkada commented on src/peft/peft_model.py
> +                filename, device=kwargs.get("device_map", "cuda" if torch.cuda.is_available() else "cpu")
Note also that `device_map` can be also a dict of strs

2023-08-23 12:31 UTC, BenjaminBossan commented
@zhangyilun Are you still working on this?

2023-08-30 20:59 UTC, zhangyilun commented
@younesbelkada Thanks for the feedback, I think it makes sense. Let me think about it.
@BenjaminBossan Yes, I can still work on this. I wasn't checking github inbox regularly enough. I will get back to this asap.

2023-10-13 15:04 UTC, closed without merging